import { OurImpactType } from "@/lib/type";
import {
  ChartIcon,
  MonitorIcon,
  OfficeBuildingIcon,
  OpenBookIcon,
  PremiumAnalyticsIcon,
  ShootingStarIcon,
  UsersIcon,
  UserWithStarIcon,
} from "./svgIcons/Icons";
import { group } from "console";
import NeuroscienceResearchLeadLogo from "@/public/images/company-logo-1.png";
import ClinicalPsychologistLogo from "@/public/images/company-logo-2.png";
import LicensedCounselorLogo from "@/public/images/company-logo-3.png";
import BehavioralAnalystLogo from "@/public/images/company-logo-4.png";
import institutionLogo1 from "@/public/images/company-logo-4.png";
import institutionLogo2 from "@/public/images/university_of_bos.png";
import institutionLogo3 from "@/public/images/university_of_cali.png";
import institutionLogo4 from "@/public/images/company-logo-1.png";
import institutionLogo5 from "@/public/images/company-logo-2.png";
import institutionLogo6 from "@/public/images/university_of_mis.png";
import institutionLogo7 from "@/public/images/university_of_tex.png";

export const landingPageFeatures = [
  {
    id: 1,
    title: "Professional Networking",
    description:
      "Connect with peers, mentors, industry leaders in psychology and neuroscience. Build meaningful relationships that advance yor Career.",
    icon: UsersIcon,
    iconBgColor: "bg-[#BCF3FB]",
    cardBgColor: "bg-[#E2FBFF]",
  },
  {
    id: 2,
    title: "Career Opportunities",
    description:
      "Browse curated job listings from top institutions and organizations. Find positions that mulch your expertise and career goals.",
    icon: MonitorIcon,
    iconBgColor: "bg-[#0145DB1A]",
    cardBgColor: "bg-[#E4EEFF]",
  },
  {
    id: 3,
    title: "Knowledge Sharing",
    description:
      "Share your research, insights, and expertise wth the community. Learn from others and stay updated on the latest developments.",
    icon: OpenBookIcon,
    iconBgColor: "bg-[#9F77C62B]",
    cardBgColor: "bg-[#F8F2FF]",
  },
  {
    id: 4,
    title: "Research Collaboration",
    description:
      "Create groups to collaborate and advance your research in a budget-constrained reality.",
    icon: PremiumAnalyticsIcon,
    iconBgColor: "bg-[#C1F9EF]",
    cardBgColor: "bg-[#EBFFFA]",
  },
];

export const howWeWorkSteps = [
  {
    id: "1",
    title: "Create Your Profile",
    description:
      "Build a professional profile that reflects your academic and career journey. Add education, experience, skills, certifications, achievements, and resumes to showcase your expertise to professionals and companies.",
  },
  {
    id: "2",
    title: "Explore Programs by Location",
    description:
      "Find the right universities and programs near you with our interactive map. Browse state-wise options and explore psychology, neuroscience, and counseling programs. Click any listing to view details.",
  },
  {
    id: "3",
    title: "Connect and Engage",
    description:
      "Grow your network within a focused professional community. Connect with professionals, researchers, and organizations. Share updates, research, and insights to stay active, visible, and build meaningful connections.",
  },
  {
    id: "4",
    title: "Apply and Grow Your Career",
    description:
      "Turn connections and discovery into real opportunities. Apply for relevant jobs, track applications, boost profile visibility, and access premium tools designed to accelerate your career growth.",
  },
];

export const opportunities = [
  {
    id: "1",
    job_title: "Neuroscience Research Lead",
    company_name: "Johns Hopkins University",
    company_logo: NeuroscienceResearchLeadLogo,
    location: "Baltimore, MD 21218, United States",
    created_at: "2026-03-25T10:00:00Z",
    job_field: "neuroscience",
    job_type: "full-time",
    job_position: "leadership",
    isSaved: false,
  },
  {
    id: "2",
    job_title: "Clinical Psychologist",
    company_name: "Stanford University",
    company_logo: ClinicalPsychologistLogo,
    location: "Stanford, CA 94305, United States",
    created_at: "2026-04-02T10:00:00Z",
    job_field: "clinical",
    job_type: "full-time",
    job_position: "research",
    isSaved: false,
  },
  {
    id: "3",
    job_title: "Licensed Counselor",
    company_name: "Penn State University",
    company_logo: LicensedCounselorLogo,
    location: "Cambridge, MA 02139, United States",
    created_at: "2026-04-10T10:00:00Z",
    job_field: "counselling",
    job_type: "part-time",
    job_position: "remote",
    isSaved: false,
  },
  {
    id: "4",
    job_title: "Behavioral Analyst",
    company_name: "University of Washington",
    company_logo: BehavioralAnalystLogo,
    location: "Seattle, WA 98195, United States",
    created_at: "2026-04-16T10:00:00Z",
    job_field: "behavioral",
    job_type: "full-time",
    job_position: "analysis",
    isSaved: false,
  },
];

export const ourImpactData: OurImpactType[] = [
  {
    id: "1",
    title: "Professionals Joined",
    description: "Growing community of experts",
    value: "500",
    Icon: UserWithStarIcon,
    uniqueKey: "professionals_joined",
    bgColor: "bg-[#E2FBFF]",
    IconBgColor: "bg-[#BCF3FB]",
  },
  {
    id: "2",
    title: "Organizations Acive",
    description: "Top institutions and companies",
    value: "200",
    Icon: OfficeBuildingIcon,
    uniqueKey: "organizations_active",
    bgColor: "bg-[#E4EEFF]",
    IconBgColor: "bg-[#CEDEFC]",
  },
  {
    id: "3",
    title: "Research Articles",
    description: "Shared insights studies",
    value: "50",
    Icon: ChartIcon,
    uniqueKey: "research_articles",
    bgColor: "bg-[#F8F2FF]",
    IconBgColor: "bg-[#E9DDF6]",
  },
  {
    id: "4",
    title: "Satisfaction Rate",
    description: "From community members",
    value: "95",
    Icon: ShootingStarIcon,
    uniqueKey: "satisfaction_rate",
    bgColor: "bg-[#EBFFFA]",
    IconBgColor: "bg-[#C1F9EF]",
  },
];

export const trustedLeadingInstitutions = [
  institutionLogo1,
  institutionLogo2,
  institutionLogo3,
  institutionLogo4,
  institutionLogo5,
  institutionLogo6,
  institutionLogo7,
];

export const features = [
  "Free professional profile",
  "Access to exclusive job listings",
  "Connect with industry leaders",
  "Share your research and insights",
];

export const usaMapData = [
  { id: "al", name: "Alabama", value: 47 },
  { id: "ak", name: "Alaska", value: 83 },
  { id: "az", name: "Arizona", value: 62 },
  { id: "ar", name: "Arkansas", value: 31 },
  { id: "ca", name: "California", value: 95 },
  { id: "co", name: "Colorado", value: 74 },
  { id: "ct", name: "Connecticut", value: 28 },
  { id: "de", name: "Delaware", value: 53 },
  { id: "fl", name: "Florida", value: 88 },
  { id: "ga", name: "Georgia", value: 41 },
  { id: "hi", name: "Hawaii", value: 19 },
  { id: "id", name: "Idaho", value: 66 },
  { id: "il", name: "Illinois", value: 39 },
  { id: "in", name: "Indiana", value: 77 },
  { id: "ia", name: "Iowa", value: 24 },
  { id: "ks", name: "Kansas", value: 82 },
  { id: "ky", name: "Kentucky", value: 55 },
  { id: "la", name: "Louisiana", value: 43 },
  { id: "me", name: "Maine", value: 91 },
  { id: "md", name: "Maryland", value: 37 },
  { id: "ma", name: "Massachusetts", value: 68 },
  { id: "mi", name: "Michigan", value: 59 },
  { id: "mn", name: "Minnesota", value: 72 },
  { id: "ms", name: "Mississippi", value: 26 },
  { id: "mo", name: "Missouri", value: 84 },
  { id: "mt", name: "Montana", value: 15 },
  { id: "ne", name: "Nebraska", value: 49 },
  { id: "nv", name: "Nevada", value: 63 },
  { id: "nh", name: "New Hampshire", value: 71 },
  { id: "nj", name: "New Jersey", value: 44 },
  { id: "nm", name: "New Mexico", value: 34 },
  { id: "ny", name: "New York", value: 92 },
  { id: "nc", name: "North Carolina", value: 57 },
  { id: "nd", name: "North Dakota", value: 18 },
  { id: "oh", name: "Ohio", value: 76 },
  { id: "ok", name: "Oklahoma", value: 38 },
  { id: "or", name: "Oregon", value: 64 },
  { id: "pa", name: "Pennsylvania", value: 85 },
  { id: "ri", name: "Rhode Island", value: 22 },
  { id: "sc", name: "South Carolina", value: 51 },
  { id: "sd", name: "South Dakota", value: 33 },
  { id: "tn", name: "Tennessee", value: 69 },
  { id: "tx", name: "Texas", value: 98 },
  { id: "ut", name: "Utah", value: 45 },
  { id: "vt", name: "Vermont", value: 13 },
  { id: "va", name: "Virginia", value: 56 },
  { id: "wa", name: "Washington", value: 79 },
  { id: "wv", name: "West Virginia", value: 29 },
  { id: "wi", name: "Wisconsin", value: 67 },
  { id: "wy", name: "Wyoming", value: 42 },
  { id: "dc", name: "District of Columbia", value: 87 },
];

export const usaStateKeyToNameMap: Record<string, string> = {
  AL: "Alabama",
  AK: "Alaska",
  AZ: "Arizona",
  AR: "Arkansas",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DE: "Delaware",
  FL: "Florida",
  GA: "Georgia, USA",
  HI: "Hawaii",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  IA: "Iowa",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  ME: "Maine",
  MD: "Maryland",
  MA: "Massachusetts",
  MI: "Michigan",
  MN: "Minnesota",
  MS: "Mississippi",
  MO: "Missouri",
  MT: "Montana",
  NE: "Nebraska",
  NV: "Nevada",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NY: "new york state",
  NC: "North Carolina",
  ND: "North Dakota",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvania",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VT: "Vermont",
  VA: "Virginia",
  WA: "Washington state",
  WV: "West Virginia",
  WI: "Wisconsin",
  WY: "Wyoming",
  WADC: "Washington DC",
};

export const Limits = [10, 25, 50, 100];

export const hospitalData = [
  {
    id: 1,
    name: "Massachusetts General Hospital",
    degrees: "MD, PhD, Post-Doc",
    lat: 42.3625,
    lng: -71.0694,
    website: "https://www.massgeneral.org",
    admissionOpen: true,
    nextSession: "Sept 2026",
  },
  {
    id: 2,
    name: "Johns Hopkins Hospital",
    degrees: "MD, PhD, MSN",
    lat: 39.2965,
    lng: -76.5925,
    website: "https://www.hopkinsmedicine.org",
    admissionOpen: false,
    nextSession: "Jan 2027",
  },
  {
    id: 3,
    name: "Mayo Clinic Hospital",
    degrees: "MD, PhD",
    lat: 44.0225,
    lng: -92.4666,
    website: "https://www.mayoclinic.org",
    admissionOpen: true,
    nextSession: "July 2026",
  },
  {
    id: 4,
    name: "Cleveland Clinic",
    degrees: "MD, MS, PhD",
    lat: 41.5014,
    lng: -81.62,
    website: "https://my.clevelandclinic.org",
    admissionOpen: true,
    nextSession: "Aug 2026",
  },
  {
    id: 5,
    name: "UCSF Medical Center",
    degrees: "MD, PhD, PharmD",
    lat: 37.7631,
    lng: -122.4578,
    website: "https://www.ucsfhealth.org",
    admissionOpen: true,
    nextSession: "Sept 2026",
  },
  {
    id: 6,
    name: "New York-Presbyterian Hospital",
    degrees: "MD, PhD",
    lat: 40.8415,
    lng: -73.9424,
    website: "https://www.nyp.org",
    admissionOpen: true,
    nextSession: "Aug 2026",
  },
  {
    id: 7,
    name: "UCLA Health-Santa Monica",
    degrees: "MD, PhD, MSN",
    lat: 34.0305,
    lng: -118.4842,
    website: "https://www.uclahealth.org",
    admissionOpen: true,
    nextSession: "Sept 2026",
  },
  {
    id: 8,
    name: "Stanford Health Care",
    degrees: "MD, PhD",
    lat: 37.4355,
    lng: -122.1764,
    website: "https://stanfordhealthcare.org",
    admissionOpen: false,
    nextSession: "Jan 2027",
  },
  {
    id: 9,
    name: "Duke University Hospital",
    degrees: "MD, PhD, PA",
    lat: 36.0069,
    lng: -78.9376,
    website: "https://www.dukehealth.org",
    admissionOpen: true,
    nextSession: "Aug 2026",
  },
  {
    id: 10,
    name: "University of Michigan Health",
    degrees: "MD, PhD, PharmD",
    lat: 42.2828,
    lng: -83.7291,
    website: "https://www.uofmhealth.org",
    admissionOpen: true,
    nextSession: "Sept 2026",
  },
  {
    id: 11,
    name: "Brigham and Women's Hospital",
    degrees: "MD, PhD",
    lat: 42.3359,
    lng: -71.1075,
    website: "https://www.brighamandwomens.org",
    admissionOpen: true,
    nextSession: "July 2026",
  },
  {
    id: 12,
    name: "Barnes-Jewish Hospital",
    degrees: "MD, PhD, MSN",
    lat: 38.636,
    lng: -90.2641,
    website: "https://www.barnesjewish.org",
    admissionOpen: true,
    nextSession: "Aug 2026",
  },
  {
    id: 13,
    name: "Northwestern Memorial Hospital",
    degrees: "MD, PhD",
    lat: 41.8949,
    lng: -87.6208,
    website: "https://www.nm.org",
    admissionOpen: true,
    nextSession: "Sept 2026",
  },
  {
    id: 14,
    name: "Mount Sinai Hospital",
    degrees: "MD, PhD",
    lat: 40.7895,
    lng: -73.9537,
    website: "https://www.mountsinai.org",
    admissionOpen: false,
    nextSession: "Feb 2027",
  },
  {
    id: 15,
    name: "UPMC Presbyterian",
    degrees: "MD, PhD, MSN",
    lat: 40.441,
    lng: -79.961,
    website: "https://www.upmc.com",
    admissionOpen: true,
    nextSession: "Aug 2026",
  },
  {
    id: 16,
    name: "Emory University Hospital",
    degrees: "MD, PhD, MPH",
    lat: 33.7918,
    lng: -84.3218,
    website: "https://www.emoryhealthcare.org",
    admissionOpen: true,
    nextSession: "Sept 2026",
  },
  {
    id: 17,
    name: "Vanderbilt University Medical Center",
    degrees: "MD, PhD",
    lat: 36.142,
    lng: -86.8005,
    website: "https://www.vumc.org",
    admissionOpen: true,
    nextSession: "July 2026",
  },
  {
    id: 18,
    name: "Cedars-Sinai Medical Center",
    degrees: "MD, PhD",
    lat: 34.0754,
    lng: -118.38,
    website: "https://www.cedars-sinai.org",
    admissionOpen: true,
    nextSession: "Aug 2026",
  },
  {
    id: 19,
    name: "Yale New Haven Hospital",
    degrees: "MD, PhD",
    lat: 41.304,
    lng: -72.936,
    website: "https://www.ynhh.org",
    admissionOpen: true,
    nextSession: "Sept 2026",
  },
  {
    id: 20,
    name: "Houston Methodist Hospital",
    degrees: "MD, PhD",
    lat: 29.7118,
    lng: -95.3986,
    website: "https://www.houstonmethodist.org",
    admissionOpen: true,
    nextSession: "Aug 2026",
  },
];

export const universityData = [
  {
    id: 1,
    name: "Harvard University",
    degrees: "BA, MA, PhD",
    lat: 42.377,
    lng: -71.1167,
    website: "https://www.harvard.edu",
    admissionOpen: true,
    nextSession: "Aug 2026",
  },
  {
    id: 2,
    name: "Stanford University",
    degrees: "BS, MS, PhD",
    lat: 37.4275,
    lng: -122.1697,
    website: "https://www.stanford.edu",
    admissionOpen: true,
    nextSession: "Sept 2026",
  },
  {
    id: 3,
    name: "Yale University",
    degrees: "BA, PhD",
    lat: 41.3111,
    lng: -72.9267,
    website: "https://www.yale.edu",
    admissionOpen: true,
    nextSession: "Aug 2026",
  },
  {
    id: 4,
    name: "Princeton University",
    degrees: "BA, PhD",
    lat: 40.3431,
    lng: -74.6551,
    website: "https://www.princeton.edu",
    admissionOpen: false,
    nextSession: "Aug 2027",
  },
  {
    id: 5,
    name: "University of Pennsylvania",
    degrees: "BA, MA, PhD",
    lat: 39.9522,
    lng: -75.1932,
    website: "https://www.upenn.edu",
    admissionOpen: true,
    nextSession: "Sept 2026",
  },
  {
    id: 6,
    name: "Columbia University",
    degrees: "BA, MA, PhD",
    lat: 40.8075,
    lng: -73.9626,
    website: "https://www.columbia.edu",
    admissionOpen: true,
    nextSession: "Aug 2026",
  },
  {
    id: 7,
    name: "UC Berkeley",
    degrees: "BA, PhD",
    lat: 37.8715,
    lng: -122.273,
    website: "https://www.berkeley.edu",
    admissionOpen: true,
    nextSession: "Aug 2026",
  },
  {
    id: 8,
    name: "University of Chicago",
    degrees: "BA, MA, PhD",
    lat: 41.7886,
    lng: -87.5987,
    website: "https://www.uchicago.edu",
    admissionOpen: true,
    nextSession: "Sept 2026",
  },
  {
    id: 9,
    name: "MIT",
    degrees: "BS, PhD",
    lat: 42.3601,
    lng: -71.0942,
    website: "https://www.mit.edu",
    admissionOpen: true,
    nextSession: "Sept 2026",
  },
  {
    id: 10,
    name: "Cornell University",
    degrees: "BA, MS, PhD",
    lat: 42.4476,
    lng: -76.4833,
    website: "https://www.cornell.edu",
    admissionOpen: true,
    nextSession: "Aug 2026",
  },
  {
    id: 11,
    name: "University of Michigan",
    degrees: "BA, PhD",
    lat: 42.278,
    lng: -83.7382,
    website: "https://umich.edu",
    admissionOpen: true,
    nextSession: "Sept 2026",
  },
  {
    id: 12,
    name: "Duke University",
    degrees: "BA, PhD",
    lat: 36.0014,
    lng: -78.9382,
    website: "https://www.duke.edu",
    admissionOpen: true,
    nextSession: "Aug 2026",
  },
  {
    id: 13,
    name: "Northwestern University",
    degrees: "BA, MA, PhD",
    lat: 42.0565,
    lng: -87.6753,
    website: "https://www.northwestern.edu",
    admissionOpen: true,
    nextSession: "Sept 2026",
  },
  {
    id: 14,
    name: "Johns Hopkins University",
    degrees: "BA, MA, PhD",
    lat: 39.3299,
    lng: -76.6205,
    website: "https://www.jhu.edu",
    admissionOpen: true,
    nextSession: "Aug 2026",
  },
  {
    id: 15,
    name: "NYU",
    degrees: "BA, MA, PhD",
    lat: 40.7295,
    lng: -73.9965,
    website: "https://www.nyu.edu",
    admissionOpen: true,
    nextSession: "Sept 2026",
  },
  {
    id: 16,
    name: "Washington University in St. Louis",
    degrees: "BA, PhD",
    lat: 38.6488,
    lng: -90.3048,
    website: "https://wustl.edu",
    admissionOpen: true,
    nextSession: "Aug 2026",
  },
  {
    id: 17,
    name: "Emory University",
    degrees: "BA, PhD",
    lat: 33.7971,
    lng: -84.3222,
    website: "https://www.emory.edu",
    admissionOpen: true,
    nextSession: "Sept 2026",
  },
  {
    id: 18,
    name: "Brown University",
    degrees: "BA, PhD",
    lat: 41.8268,
    lng: -71.4025,
    website: "https://www.brown.edu",
    admissionOpen: true,
    nextSession: "Aug 2026",
  },
  {
    id: 19,
    name: "Rice University",
    degrees: "BA, PhD",
    lat: 29.7174,
    lng: -95.4018,
    website: "https://www.rice.edu",
    admissionOpen: true,
    nextSession: "Aug 2026",
  },
  {
    id: 20,
    name: "University of Virginia",
    degrees: "BA, MA, PhD",
    lat: 38.0336,
    lng: -78.508,
    website: "https://www.virginia.edu",
    admissionOpen: true,
    nextSession: "Sept 2026",
  },
];
